### ISSUE TITLE
Error download pacemaker

### ISSUE THREAD

**Issue by SmileoAR** [kskmori/ansible-pacemaker#3]
TASK [Download pacemaker-repo-1.1] *******************************************************************************************************************************************************************************************************************************************
failed: [192.168.109.130] (item={u'rev': 69021, u'package': u'pacemaker-repo-1.1.17-1.1.el7.x86_64.rpm'}) => {"changed": false, "item": {"package": "pacemaker-repo-1.1.17-1.1.el7.x86_64.rpm", "rev": 69021}, "msg": "Failed to connect to osdn.net at port 443: [Errno -2] Имя или служба не известны"}
failed: [192.168.109.130] (item={u'rev': 69021, u'package': u'pacemaker-repo-debuginfo-1.1.17-1.1.el7.x86_64.rpm'}) => {"changed": false, "item": {"package": "pacemaker-repo-debuginfo-1.1.17-1.1.el7.x86_64.rpm", "rev": 69021}, "msg": "Failed to connect to osdn.net at port 443: [Errno -2] Имя или служба не известны"}
failed: [192.168.109.130] (item={u'rev': 69022, u'package': u'pacemaker-repo-1.1.17-1.1.el6.x86_64.rpm'}) => {"changed": false, "item": {"package": "pacemaker-repo-1.1.17-1.1.el6.x86_64.rpm", "rev": 69022}, "msg": "Failed to connect to osdn.net at port 443: [Errno -2] Имя или служба не известны"}
failed: [192.168.109.130] (item={u'rev': 69022, u'package': u'pacemaker-repo-debuginfo-1.1.17-1.1.el6.x86_64.rpm'}) => {"changed": false, "item": {"package": "pacemaker-repo-debuginfo-1.1.17-1.1.el6.x86_64.rpm", "rev": 69022}, "msg": "Failed to connect to osdn.net at port 443: [Errno -2] Имя или служба не известны"}
failed: [192.168.109.129] (item={u'rev': 69021, u'package': u'pacemaker-repo-1.1.17-1.1.el7.x86_64.rpm'}) => {"changed": false, "item": {"package": "pacemaker-repo-1.1.17-1.1.el7.x86_64.rpm", "rev": 69021}, "msg": "Destination ./roles/pacemaker-install/files does not exist"}
failed: [192.168.109.129] (item={u'rev': 69021, u'package': u'pacemaker-repo-debuginfo-1.1.17-1.1.el7.x86_64.rpm'}) => {"changed": false, "item": {"package": "pacemaker-repo-debuginfo-1.1.17-1.1.el7.x86_64.rpm", "rev": 69021}, "msg": "Destination ./roles/pacemaker-install/files does not exist"}
failed: [192.168.109.129] (item={u'rev': 69022, u'package': u'pacemaker-repo-1.1.17-1.1.el6.x86_64.rpm'}) => {"changed": false, "item": {"package": "pacemaker-repo-1.1.17-1.1.el6.x86_64.rpm", "rev": 69022}, "msg": "Destination ./roles/pacemaker-install/files does not exist"}
failed: [192.168.109.129] (item={u'rev': 69022, u'package': u'pacemaker-repo-debuginfo-1.1.17-1.1.el6.x86_64.rpm'}) => {"changed": false, "item": {"package": "pacemaker-repo-debuginfo-1.1.17-1.1.el6.x86_64.rpm", "rev": 69022}, "msg": "Destination ./roles/pacemaker-install/files does not exist"}

**Comment by kskmori** [comment]
@SmileoAR Hi,

> "Failed to connect to osdn.net at port 443: [Errno -2] Имя или служба не известны"

It seems like a network connectivity issue between your host and osdn.net, or maybe a proxy configuration issue etc. By the way, I have never imagined that people of Cyrillic language use my repository :)

> "Destination ./roles/pacemaker-install/files does not exist"

It is strange. That directory should be created when you `git clone`ed the repo. How did you clone it? Would you try it again from the beginning with a fresh working copy and see if it still occurs and if the directory is created? 

Thanks,

**Comment by kskmori** [comment]
Closing, as there was no actions for very long time.
Please file a new issue if there is still a problem. Thanks,
