### ISSUE TITLE
An error occurs with roles/test-link-disconnect/tasks/iptables.yml.

### ISSUE THREAD

**Issue by adelie2000** [kskmori/ansible-pacemaker#5]
I tried to run the shell part of task "- name: obtain NIC names", I could not get the nic name.
I think you need to fix the sed part.

## NG

```
# ip -o route get 192.168.113.0  | sed -e "s/^.*\sdev\s\([^\s]*\)\s.*$/\1/"
broadcast 192.168.113.0 dev ens38 src 192.168.113.2 \    cache <local,brd>
```

## solution. 1
```
# ip -o route get 192.168.113.0 | sed -e "s/^.*\sdev\s\([^ \t]*\)\s.*$/\1/g"
ens38
```

## solution. 2
```
# ip -o route get 192.168.113.0 | sed -e "s/^.*\sdev\s\(\S*\)\s.*$/\1/g"
ens38
```

## my env

```
# sed --version
sed (GNU sed) 4.2.2

# ip -V
ip utility, iproute2-ss170501

# cat /etc/redhat-release
CentOS Linux release 7.8.2003 (Core)

# uname -r
3.10.0-1127.13.1.el7.x86_64
```

**Comment by kskmori** [comment]
@adelie2000 
Thank you very much for your report and the detailed information! It help me a lot.

I was not aware that `\s` in GNU sed does not work as expected in `[]` like perl.
Please find 894b0f7 for the fix as you've suggested in solution 2.

Thanks,

**Comment by kskmori** [comment]
Notes for the future references - `\s` behavior in GNU sed:

* matching to spaces - expected
```
$ echo "a s z" | sed -e "s/\s/_/g"
a_s_z
```
* matching to spaces with brackets - not expected
```
]$ echo "a s z" | sed -e "s/[\s]/_/g"
a _ z
```
* matching to non-spaces - not expected
```
$ echo "a s z" | sed -e "s/[^\s]/_/g"
__s__
```
* matching to non-spaces - expected
```
$ echo "a s z" | sed -e "s/\S/_/g"
_ _ _
$ echo "a s z" | perl -pe "s/[^\s]/_/g"
_ _ _
```
